### ISSUE TITLE
cite request

### ISSUE THREAD

**Issue by kishanpb** [Laixishi/Robust-RL-with-KL-divergence#1]
Nice work for the finite horizon! Thanks for the citation in the paper. Can you also please kindly cite our [github](https://github.com/kishanpb/RobustRL) code? 
Thanks!

**Comment by Laixishi** [comment]
Hi Kishan,

Thanks for your praise for our work. Your work is also very impressive and novel. We have already added the link to your code link reference on [Github](https://github.com/Laixishi/Robust-RL-with-KL-divergence). We will also add it properly in the revision of our paper. Thank you!

Best,
Laixi
